### ISSUE TITLE
Simplify Travis build matrix

### ISSUE THREAD

**Issue by skalee** [riboseinc/activeuuid#10]
At the moment, this gem's Travis build matrix is a Cartesian product of Ruby versions, Rails versions, and database backends.  54 build jobs in total, and certainly more in future. This should be simplified.

**Comment by ribose-jeffreylau** [comment]
Agreed!  How should this be approached?

**Comment by skalee** [comment]
Like we do in other projects, e.g. https://github.com/riboseinc/attr_masker/blob/master/.travis.yml

**Comment by ronaldtse** [comment]
Sounds good. @skalee could you help achieve this? Thanks!

**Comment by skalee** [comment]
Fixed by #29.
