### ISSUE TITLE
Gem name and metadata

### ISSUE THREAD

**Issue by skalee** [riboseinc/activeuuid#11]
This gem is forked from https://github.com/jlsookiki/activeuuid which is a fork of https://github.com/inbeom/activeuuid which is a fork of https://github.com/jashmenn/activeuuid. The last one is an original source, but the most recent commit on master is from 2 Sep 2015, also 10 pull requests are open and not merged in. On the other hand, the original author is still active on GitHub, and was commenting these pull requests in 2017. But again, his comments from August are like he is willing to add more collaborators to activeuuid project, and even allow them to push new versions to RubyGems.

In these circumstances, a couple of questions rise:
1. Do we plan to create pull requests in the original repository, and perhaps ask for contributor privileges? Or continue maintaining activeuuid in riboseinc/activeuuid?
2. If the latter, do we want to release gem to RubyGems under new name? Then what name? `activeuuid_riboseinc`, perhaps?

**Comment by ronaldtse** [comment]
Thanks @skalee 

1. From what I see in the code a lot of things could be stripped away in Rails 5
2. We may want to adopt the simpler approach of https://github.com/nedap/mysql-binuuid-rails
3. There are things that don't / won't work without large changes, such as to achieve Emoji dumping using @ribose-jeffreylau 's schema dumper.

Would you consider forking / streamlining / reviving this as a completely separate gem, or do you think the value of doing so is rather minimal?

**Comment by skalee** [comment]
@ronaldtse @ribose-jeffreylau Why not http://edgeguides.rubyonrails.org/active_record_postgresql.html#uuid? I've noticed that your primary concern is PostgreSQL.

**Comment by skalee** [comment]
I agree that `activeuuid` gem is full of legacy-looking things which could be stripped away. I agree that there are lots of things to be removed, added, or improved. The main advantage of `activeuuid` gem is that it has drawn a lot attention already, like [half a million of downloads](https://rubygems.org/gems/activeuuid).

However, if it doesn't matter much, I'd even consider rewriting it from scratch in a clean way, without so many monkey patches.

**Comment by skalee** [comment]
Regarding Emoji dumping, I have no idea what do you mean by that.

**Comment by ribose-jeffreylau** [comment]
@skalee Regarding "emoji dumping", I think it is in reference to a monkey patch we did internally for Rails' [schema_dumper.rb](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/schema_dumper.rb), where we override `#header` to also print out Ruby code in a project's `db/schema.rb` to change `innodb_large_prefix` to `on`.  Historically speaking, it would also override the dumper to make the printing of UUID column definitions work, but this particular monkey-patch is now unnecessary.

As for https://github.com/nedap/mysql-binuuid-rails, I don't quite like the fact that UUIDs are deserialized as `String` in Ruby, as opposed to `UUID`.  Maybe there are other benefits to `String`, but I think being a `UUID` provides more meaning to it than a `String` does.

Regarding making it into a separate gem vs merging back upstream, I'm for the latter, as it seems that the author is willing to accept patches, judging from the original repos PRs comments.  Though, I think rewriting in a clean way can still be an option.  Maybe even merge the clean rewrite back upstream ??? 😳 Just a thought.

**Comment by skalee** [comment]
OK then. The only potential problem I see so far is that the original gem supports Ruby 1.9.3, whereas your improvements rely on `Module#prepend`, which was unavailable back then. I hope the original author won't mind dropping support for 1.9.3.

**Comment by ronaldtse** [comment]
I agree with the string part about mysql-binuuid-rails, but I thought it used a more native way for Rails 5 given that Rails 5 has support for UUIDs in postgres?

Fine with merging back upstream -- if it's taking long or not working we can always fork out again (or rewrite).

**Comment by skalee** [comment]
`mysql-binuuid-rails` does not support PostgreSQL at all.  They say that one should use pure Rails which supports pg features. And according to [Rails guides](http://edgeguides.rubyonrails.org/active_record_postgresql.html#uuid), regular strings are used to represent UUIDs in Ruby code.

**Comment by skalee** [comment]
I thought a bit and now I'm leaning toward opinion that the best solution is to create a feature request or pull request in Rails repository with following changes:

1. Turn the `Digest::UUID` module which is [defined in Rails](https://github.com/rails/rails/blob/3fdfe21db8c295a2805e6b137a9599d46dbc67df/activesupport/lib/active_support/core_ext/digest/uuid.rb) into a class (Ruby stdlib's `Digest::MD5` or `Digest::HMAC` are classes already)
2. Implement comparison methods, like `#==`
3. Use them instead of regular strings in ActiveRecord

The third step is a breaking change, so even if accepted by Rails team, it is unlikely to appear prior Rails 6. So I believe I will have to do some work in this gem as well.

Opinions?

**Comment by ribose-jeffreylau** [comment]
@skalee Making Rails work by default seems like the most natural way, in the longer run at least.  Yes, before that, we'll have to rely on this gem.

**Comment by ronaldtse** [comment]
Agree with the approach. I mentioned PG because rails 5 supports PG UUIDs by default and technically does not need this gem.

**Comment by skalee** [comment]
Few days ago I've submitted a [feature proposal](https://groups.google.com/forum/?fromgroups=#!topic/rubyonrails-core/l5BHvpysyT4) to rubyonrails-core mailing group. No  responses so far.

**Comment by ribose-jeffreylau** [comment]
Fingers crossed! 🤞

**Comment by skalee** [comment]
@ronaldtse @ribose-jeffreylau, is there any reason, weak or strong, to support Rails < 4.2? I am thinking about major overhaul, if not rewriting from scratch using up-to-date Rails API. Be advised that upcoming rails-keyserver will be also affected (the only gem I know which depends on this one).

**Comment by skalee** [comment]
<s>Also, is there a weak or good reason to represent UUIDs as `UUIDTools::UUID` instances from https://github.com/sporkmonger/uuidtools instead of regular strings? I am thinking of removing this dependency.</s>

Scratch that. @ribose-jeffreylau has answered on that question already here: https://github.com/riboseinc/activeuuid/issues/11#issuecomment-365132374.

**Comment by ronaldtse** [comment]
Thanks @skalee 😉

**Comment by ribose-jeffreylau** [comment]
Thanks @skalee !  I don't think there are any strong reasons to support Rails < 4.2.

**Comment by ronaldtse** [comment]
@skalee with the complete rewrite, it may be time to rename the gem to something else. 

First we need an update of the README to reflect its current state.

**Comment by ronaldtse** [comment]
Maybe @opoudjis is happy to provide us with an educated name...

**Comment by skalee** [comment]
Two ugly ideas: `ribose_activeuuid`, `activeuuid2`. Apart from them, `uuid_column`. Neither is taken on RubyGems.

**Comment by skalee** [comment]
Just wanted to remind about this one.

**Comment by skalee** [comment]
Another idea: `activeuuid_rewrite`. I think it's a good idea to keep "activeuuid" part in gem name.

**Comment by ronaldtse** [comment]
How about just `activeuid`?

**Comment by skalee** [comment]
With single `u`? Cause `activeuuid` is already taken.

**Comment by skalee** [comment]
Rails 5.2 compatibility has been fixed, a detailed documentation with usage examples has been written, and everything is covered with tests. The only thing what prevents us from releasing it to public is lack of good name.

Few new proposals: `activeuuid5` (5 as in Rails 5), `activeuuid_again`, `attr_uuid` (although I don't like it, it suggests an attribute setter/getter), `uuid_type`, `uuids_for_rails`.

Opinions? Suggestions?

**cc** @ronaldtse @ribose-jeffreylau @opoudjis

**Comment by ribose-jeffreylau** [comment]
What about `active_uid`?

- Putting an underscore there to be consistent with other Ruby gems,
- using a single `u` in `uid` since we also cater for non-universal `uid`s,
- keeping the "`active`" for searchability.

**Comment by ronaldtse** [comment]
Agree with @ribose-jeffreylau 😉

**Comment by skalee** [comment]
> * Putting an underscore there to be consistent with other Ruby gems,

Actually, gem names of Rails components are lacking an underscore, e.g. https://rubygems.org/gems/activerecord, or https://rubygems.org/gems/activestorage. The module name, on the other hand, is `ActiveRecord`, which requires by convention underscores in file paths.

> * using a single u in uid since we also cater for non-universal uids,

Any more info about this? I don't think we support non-universal uids. Unless they look like uuids, but in such case I see no good reason to use non-universal identifiers.

> * keeping the "active" for searchability.

I suppose that people will search for "active_uuid" or "uuid" rather than "active". Nevertheless, we should preserve `activeuuid` in gem summary and wherever possible for searchability.

BTW Just came up with an idea: `space_uuidity`.

**Comment by ronaldtse** [comment]
@skalee this was overdue. Sorry about that. Let's call it "ActiveUID" (`activeuid`) while we still utilize UUIDs.

> Actually, gem names of Rails components are lacking an underscore, e.g. https://rubygems.org/gems/activerecord, or https://rubygems.org/gems/activestorage. The module name, on the other hand, is ActiveRecord, which requires by convention underscores in file paths.

Agreed.

> Any more info about this? I don't think we support non-universal uids. Unless they look like uuids, but in such case I see no good reason to use non-universal identifiers.

We don't now, but I really can't think of a better name. Maybe we can handle other types of UIDs in the future.

> I suppose that people will search for "active_uuid" or "uuid" rather than "active". Nevertheless, we should preserve activeuuid in gem summary and wherever possible for searchability.

Agree.

**Comment by ronaldtse** [comment]
Once we rename the repo, we can contact GitHub Support to "un-fork" this.

https://help.github.com/en/github/setting-up-and-managing-your-github-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork
<img width="764" alt="Screen Shot 2020-05-28 at 10 58 01 AM" src="https://user-images.githubusercontent.com/11865/83093477-1b4f9c80-a0d2-11ea-84d5-4e037e09d18b.png">

**Comment by skalee** [comment]
> @skalee this was overdue. Sorry about that. Let's call it "ActiveUID" (`activeuid`) while we still utilize UUIDs.

If you want to follow this path, perhaps `activeid`, which is even more generic.

I am not going to oppose against `activeuid` any longer though. If agreed, please rename repository. I dislike this name for numerous reasons: it looks odd like having a typo in it, it confusingly suggests to have something to do with user identifiers on Unix/Linux, and finally, actually users will search for UUIDs, not UIDs. But I can live with that.

----

BTW I've noticed that I have some sizeable work-in-progress branches in this project. Probably some unfinished features or refactoring. I guess I will take a look.

**Comment by ronaldtse** [comment]
> If you want to follow this path, perhaps activeid, which is even more generic.

Then let's go with `activeid`?

**Comment by ronaldtse** [comment]
Renamed to `activeid`. Will contact GitHub support for unforking.

**Comment by ronaldtse** [comment]
I have submitted detach fork request to GH Support. @skalee can you help update gem metadata and push the gem? Thanks.

**Comment by ronaldtse** [comment]
Done in #60.

**Comment by ronaldtse** [comment]
Thanks to GitHub support — this gem is now standalone with its own forks!

Ping @skalee
