### ISSUE TITLE
Travis CI for Rails 5 / 5.1

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/activeuuid#2]
As title. This is why we're keep having problems, and we should make sure stuff doesn't break again.

@skalee perhaps you could help? Thanks!

**Comment by skalee** [comment]
@ronaldtse Done on rails5-wip branch. The repository history is pretty complicated, and the last commit merged to master is from year ago, hence I restrained from making a pull request.

**Comment by skalee** [comment]
@ronaldtse It appears that Travis is disabled for this repository, and the badge in README points to repo this one has been forked from. Pls turn Travis on.

**Comment by ronaldtse** [comment]
@skalee Travis is on now, please help update the badge too. Thanks!

**Comment by ronaldtse** [comment]
Also, I think we should directly merge to master once things work. If there are things we can improve / cleanup, please also go ahead. Thanks!

**Comment by ribose-jeffreylau** [comment]
I think this can be closed (with 8fde9590c6a0f7397ee26943e7123860bc943e50, GH-4).
