### ISSUE TITLE
Broken tests on Ruby 2.3

### ISSUE THREAD

**Issue by skalee** [riboseinc/activeuuid#63]
Although Ruby 2.3 has reached its end of life, this gem is compatible in general, just tests fail due to some issues with `mysql2` gem.

This should be easy to fix, and perhaps downgrading `mysql2` gem will suffice. If I'm wrong, then perhaps it's best to drop support for that outdated Ruby version. At the time of writing this, the gem has been just renamed and hasn't been pushed to Rubygems since that yet, so it's a very good moment for incompatible changes.

**Comment by skalee** [comment]
Nah, simply let's drop support for that version. See #66.

**Comment by ronaldtse** [comment]
Agree!
